
##########################################
#     Change these variables !important
##########################################

# Set this for Copyright in the footer
owner: Name Surname

# Optional quote in the footer
# To disable set enable to false
quote:
  enable: true
  quote: Some fancy quote.
  author: Rudy Li

# Set this to your main site title
# In the head - ff page doesnt have its own title,
# Site title will be used instead
title: Aliquam Theme - Author Dennis Grinch

# Description and title below nav in the header
punch-line: true

# Your logo for the header
logo:
  title: Литвинцев Роман Александрович
  subtitle: Студент&Программист&Творческая Личность

include:
  - pages

# Following needed for disqus integration
# Set your 'disqus' account name
disqus:'romariozbk'

# Uncomment if deployed locally
# url: https://localhost:4000

# Set your host if deployed not locally
# For example "https://yourGitHub.github.io"
url: "https://romario.github.io"

# Change this to your base URL starting with forward slash if site is in gh-pages branch
# For example /branchName
baseurl:

# Change this to your google analytics ID
google_analytics:

# Contact form pupublic key
contact_PK:

##########################################
#          Optional variables
##########################################


# Set maximum posts per page
paginate: 5

# Set permalink
permalink: /:categories/:title

# Set excerpt separator
truncate_size: 40

##########################################
#          Do not change these variables
##########################################

sass:
  sass_dir: _sass
sass:
    style: compressed

include:
  - pages

gems:
  - jekyll-paginate
  - jekyll-sitemap # add /sitemap.xml file

paginate_path: /_pages/page:num

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
